### ISSUE TITLE
error in ulora.py line 117

### ISSUE THREAD

**Issue by LioBou** [ElektorLabs/210047-LoRa-with-the-Raspberry-Pi-Pico#1]
Hello,
after trying to make it work, it found an error on the ulora.py file:

line 117:
replace "cs" by "rst"

without it, impossible to make it work!

**Comment by calm4git** [comment]
Thanks for submitting the bugreport
A patched version will be here soon

**Comment by lab-mathias-claussen** [comment]
Thnks for the bug report. Issue has been fixed. 

Best Regards
